### ISSUE TITLE
Mistake in Assignment 4 solution

### ISSUE THREAD

**Issue by cr7ritesh** [sudarsun/DA5401-2024#6]
Hi sir,

I think there is a slight mistake in the class definition. All method = 'gaussian' objects are getting created as 'uniform_normal'. While instantiating self.method, 'normal' should be replaced by 'gaussian' in the list.

![image](https://github.com/user-attachments/assets/11d05819-834d-4ffe-b1e1-1dc7181b2c7b)

Regards,
Ritesh

**Comment by sudarsun** [comment]
You are right.  Thanks for pointing out the mistake.  I will fix it right away.

It would be impressive if you had forked the code and submitted a merge request (MR) to fix the bug. I think you should consider doing it next time.  You can also resolve the problem and raise an MR to fix the code.

**Comment by cr7ritesh** [comment]
Sure, I will try to do this next time around. Closing this issue.
